[package]
name = "audioipc-client"
version = "0.2.0"
authors = [
        "Matthew Gregan <kinetik@flim.org>",
        "Dan Glastonbury <dan.glastonbury@gmail.com>"
        ]
description = "Cubeb Backend for talking to remote cubeb server."

[dependencies]
audioipc = { path="../audioipc" }
cubeb-backend = { git="https://github.com/djg/cubeb-rs", version="^0.2" }
cubeb-core = { git="https://github.com/djg/cubeb-rs", version="^0.1" }
# rayon-core in Gecko uses futures 0.1.13
futures = { version="=0.1.13", default-features=false, features=["use_std"] }
# futures-cpupool 0.1.5 matches futures 0.1.13
futures-cpupool = { version="=0.1.5", default-features=false }
libc = "0.2"
log = "^0.3.6"
tokio-core = "0.1"
tokio-uds = "0.1.7"
audio_thread_priority = "0.3"
