[package]
name = "audioipc"
version = "0.1.0"
authors = [
        "Matthew Gregan <kinetik@flim.org>",
        "Dan Glastonbury <dan.glastonbury@gmail.com>"
        ]
description = "Remote Cubeb IPC"

[dependencies]
cubeb-core = { git = "https://github.com/djg/cubeb-rs", version="^0.1" }
bincode = "0.8"
bytes = "0.4"
error-chain = "0.11.0"
libc = "0.2"
log = "^0.3.6"
memmap = "0.5.2"
mio = "0.6.7"
mio-uds = "0.6.4"
serde = "1.*.*"
serde_derive = "1.*.*"
